# name: Build Windows EXE

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:  # يسمح لك بتشغيله يدويًا من GitHub Actions

# jobs:
#   build:
#     runs-on: windows-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.11'

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install pyinstaller
#           if (Test-Path requirements.txt) { pip install -r requirements.txt }

#       - name: Build executable
#         run: |
#           pyinstaller --onefile --windowed --name "Inventory" 'script/inventory.py'
#           pyinstaller --onefile --windowed --name "Inventory" 'script/redCSV.py'

#       - name: Upload build artifact
#         uses: actions/upload-artifact@v4
#         with:
#           name: InventoryApp-Windows
#           path: dist/InventoryApp.exe

name: Build Python Executables

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    name: Build Windows EXE
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if (Test-Path requirements.txt) { pip install -r requirements.txt }

      - name: Build Windows executables
        run: |
          pyinstaller --onefile --windowed --name "Inventory" "script/inventory.py"
          pyinstaller --onefile --windowed --name "REDCSV" "script/redCSV.py"

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: InventoryApp-Windows
          path: |
            dist/Inventory.exe
            dist/REDCSV.exe

  build-linux:
    runs-on: ubuntu-latest
    name: Build Linux Executable
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build Linux executables
        run: |
          pyinstaller --onefile --name "Inventory" "script/inventory.py"
          pyinstaller --onefile --name "REDCSV" "script/redCSV.py"

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: InventoryApp-Linux
          path: dist/*
